# Generated by Django 3.2.19 on 2023-05-28 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exhauster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='name')),
                ('description', models.CharField(blank=True, max_length=200, default='', null=True, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='SensorData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('data', models.CharField(max_length=200, verbose_name='description')),
            ],
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(verbose_name='date')),
                ('masloohloditel_m05_1_exh', models.JSONField(blank=True, null=True, verbose_name='МАСЛООХЛАДИТЕЛЬ М-05-1 ЭКСГ.')),
                ('electrodvigatel_dspu_140_84_4_exh', models.JSONField(blank=True, null=True, verbose_name='ЭЛЕКТРОДВИГАТЕЛЬ ДСПУ-140-84-4 ЭКСГ.')),
                ('korpus_exh', models.JSONField(blank=True, null=True, verbose_name='КОРПУС ЭКСГ.')),
                ('zadvizhka_exh', models.JSONField(blank=True, null=True, verbose_name='ЗАДВИЖКА ЭКСГ.')),
                ('podshipnik_oporny_exh', models.JSONField(blank=True, null=True, verbose_name='ПОДШИПНИК ОПОРНЫЙ ЭКСГ.')),
                ('podshipnik_oporno_uporny_exh', models.JSONField(blank=True, null=True, verbose_name='ПОДШИПНИК ОПОРНО-УПОРНЫЙ ЭКСГ.')),
                ('maslonasos_shesterenchatyj_rez', models.JSONField(blank=True, null=True, verbose_name='МАСЛОНАСОС ШЕСТЕРЕНЧАТЫЙ (РЕЗ.) ЭКСГ.')),
                ('vk_310s_vibropreobrazovatel_t1', models.JSONField(blank=True, null=True, verbose_name='ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ. Т.1')),
                ('vk_310s_vibropreobrazovatel_t3', models.JSONField(blank=True, null=True, verbose_name='ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ. Т.3')),
                ('elektrooborudovaniya_austera', models.JSONField(blank=True, null=True, verbose_name='ЭЛЕКТРООБОРУДОВАНИЯ ЭКСГАУСТЕРА')),
                ('vk_310s_vibropreobrazovatel_t2', models.JSONField(blank=True, null=True, verbose_name='ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ. Т.2')),
                ('podshipnik_oporny', models.JSONField(blank=True, null=True, verbose_name='ПОДШИПНИК ОПОРНЫЙ')),
                ('reduktor_gaz_zadvizhki_exh', models.JSONField(blank=True, null=True, verbose_name='РЕДУКТОР ГАЗ. ЗАДВИЖКИ ЭКСГ.')),
                ('tiristor_vozbuditel_vt_rem_400_vu1', models.JSONField(blank=True, null=True, verbose_name='ТИРИСТ. ВОЗБУДИТЕЛЬ ВТ-РЭМ-400 ВУ1')),
                ('zapornaya_armatura_exhaustera', models.JSONField(blank=True, null=True, verbose_name='ЗАПОРНАЯ АРМАТУРА ЭКСГАУСТЕРА')),
                ('masloprovody_exhaustera', models.JSONField(blank=True, null=True, verbose_name='МАСЛОПРОВОДЫ ЭКСГАУСТЕРА')),
                ('gsm_exh', models.JSONField(blank=True, null=True, verbose_name='ГСМ ЭКСГ.')),
                ('tsmt_101_010_50m_80_termopreobr_maslo', models.JSONField(blank=True, null=True, verbose_name='ТСМТ-101-010-50М-80 ТЕРМОПРЕОБР.МАСЛО')),
                ('tr_r_tm_4000_10_6_exh', models.JSONField(blank=True, null=True, verbose_name='ТР-Р ТМ-4000-10/6 ЭКСГ.')),
                ('kl1_tr_do_ed_exhaustera', models.JSONField(blank=True, null=True, verbose_name='КЛ1 ТР ДО ЭД ЭКСГАУСТЕРА')),
                ('kl2_tr_do_ed_exhaustera', models.JSONField(blank=True, null=True, verbose_name='КЛ2 ТР ДО ЭД ЭКСГАУСТЕРА')),
                ('maslonasos_rabochij_exh', models.JSONField(blank=True, null=True, verbose_name='МАСЛОНАСОС РАБОЧИЙ ЭКСГ.')),
                ('rotor_exh', models.JSONField(blank=True, null=True, verbose_name='РОТОР ЭКСГ.')),
                ('metran_100_datchiki_davleniya_exh', models.JSONField(blank=True, null=True, verbose_name='МЕТРАН-100 ДАТЧИКИ ДАВЛЕНИЯ ЭКСГ.')),
                ('dvigatel_puskovogo_maslonasosa_exh', models.JSONField(blank=True, null=True, verbose_name='ДВИГАТЕЛЬ ПУСКОВОГО МАСЛОНАСОСА ЭКСГ.')),
                ('gazovaya_zadvizhka_exhaustera_a_m', models.JSONField(blank=True, null=True, verbose_name='ГАЗОВАЯ ЗАДВИЖКА ЭКСГАУСТЕРА А/М')),
                ('kozhuh_mufty', models.JSONField(blank=True, null=True, verbose_name='КОЖУХ МУФТЫ ЭКСГ.')),
                ('tiristor_vozbuditel_vt_rem_400_vu2', models.JSONField(blank=True, null=True, verbose_name='ТИРИСТ. ВОЗБУДИТЕЛЬ ВТ-РЭМ-400 ВУ2')),
                ('tsmt_101_010_50m_400_termopr_podsh_t2', models.JSONField(blank=True, null=True, verbose_name='ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.2')),
                ('dvigatel_rezervnogo_maslonasosa_exh', models.JSONField(blank=True, null=True, verbose_name='ДВИГАТЕЛЬ РЕЗЕРВНОГО МАСЛОНАСОСА ЭКСГ.')),
                ('tsmt_101_010_50m_200_termopr_podsh_t3', models.JSONField(blank=True, null=True, verbose_name='ТСМТ-101-010-50М-200 ТЕРМОПР.ПОДШ.Т.3')),
                ('exhauster_n_8000_a_m', models.JSONField(blank=True, null=True, verbose_name='ЭКСГАУСТЕР Н-8000 А/М')),
                ('sapfir_22_mdd_razrezhenie_v_kollectore', models.JSONField(blank=True, null=True, verbose_name='САПФИР 22 МДД РАЗРЕЖЕНИЕ В КОЛЛЕКТОРЕ')),
                ('maslobak_exh', models.JSONField(blank=True, null=True, verbose_name='МАСЛОБАК ЭКСГ.')),
                ('elektrooborudovaniya', models.JSONField(blank=True, null=True, verbose_name='ЭЛЕКТРООБОРУДОВАНИЯ ЭКСГ')),
                ('sapfir_22_mdd_perepad_davl_na_ciklone', models.JSONField(blank=True, null=True, verbose_name='САПФИР 22 МДД ПЕРЕПАД ДАВЛ. НА ЦИКЛОНЕ')),
                ('tiristornyj_vozbuditel_tv_400_vu1', models.JSONField(blank=True, null=True, verbose_name='ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ ТВ-400 ВУ1')),
                ('maslonasos_shesterechchatyj_pusk', models.JSONField(blank=True, null=True, verbose_name='МАСЛОНАСОС ШЕСТЕРЕНЧАТЫЙ (ПУСК.) ЭКСГ.')),
                ('masloprovody_exh', models.JSONField(blank=True, null=True, verbose_name='МАСЛОПРОВОДЫ ЭКСГ')),
                ('ulita_exh', models.JSONField(blank=True, null=True, verbose_name='УЛИТА ЭКСГ.')),
                ('elektroapparatura_exh', models.JSONField(blank=True, null=True, verbose_name='ЭЛЕКТРОАППАРАТУРА ЭКСГ.')),
                ('tsmt_101_010_50m_400_termopr_podsh_t1', models.JSONField(blank=True, null=True, verbose_name='ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.1')),
                ('zap_i_reg_armatura_exh', models.JSONField(blank=True, null=True, verbose_name='ЗАП. И РЕГ. АРМАТУРА ЭКСГ.')),
                ('ele_dvigatel_gaz_zadvizhki_exh', models.JSONField(blank=True, null=True, verbose_name='ЭЛ/ДВИГАТЕЛЬ ГАЗ. ЗАДВИЖКИ ЭКСГ.')),
                ('maslyanyj_filtr_exhaustera', models.JSONField(blank=True, null=True, verbose_name='МАСЛЯНЫЙ ФИЛЬТР ЭКСГАУСТЕРА')),
                ('vk_310s_vibropreobrazovatel_t4_exh', models.JSONField(blank=True, null=True, verbose_name='ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ. Т.4')),
                ('reguliruyushchaya_apparatura_austera', models.JSONField(blank=True, null=True, verbose_name='РЕГУЛИРУЮЩАЯ АППАРАТУРА ЭКСГАУСТЕРА')),
                ('maslostantsiya_zhidkoj_smazki_exh', models.JSONField(blank=True, null=True, verbose_name='МАСЛОСТАНЦИЯ ЖИДКОЙ СМАЗКИ ЭКСГ.')),
                ('tr_r_tm_6300_10_6', models.JSONField(blank=True, null=True, verbose_name='ТР-Р ТМ-6300-10/6 ЭКСГ.')),
                ('tiristornyj_vozbuditel_tv_400_9_vu1', models.JSONField(blank=True, null=True, verbose_name='ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ ТВ-400 9 ВУ1')),
                ('tiristornyj_vozbuditel_spvd_m10_400_5', models.JSONField(blank=True, null=True, verbose_name='ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ СПВД-М10-400-5')),
                ('exhauster_a_m', models.JSONField(blank=True, null=True, verbose_name='ЭКСГАУСТЕР А/М')),
                ('tsmt_101_010_50m_200_termopr_podsh_t4', models.JSONField(blank=True, null=True, verbose_name='ТСМТ-101-010-50М-200 ТЕРМОПР.ПОДШ.Т.4')),
                ('exhauster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='wear.exhauster', verbose_name='statistic')),
            ],
        ),
    ]
