from django.db import models
from django.utils.translation import ugettext_lazy as _

class Exhauster(models.Model):
    name = models.CharField(max_length=200, verbose_name=_('name'))
    description = models.CharField(max_length=200, null=True, blank=True, default='', verbose_name=_('description'))
    # file = models.FileField(upload_to='static/')

class SensorData(models.Model):
    date = models.DateTimeField(verbose_name=_('date'))
    data = models.CharField(max_length=200, verbose_name=_('description'))


class Statistics(models.Model):
    date = models.DateTimeField(verbose_name=_('date'))
    exhauster = models.ForeignKey(Exhauster, on_delete=models.CASCADE, verbose_name=_('statistic'))

    masloohloditel_m05_1_exh = models.JSONField(blank=True, null=True, verbose_name=_('МАСЛООХЛАДИТЕЛЬ М-05-1 ЭКСГ.'))
    electrodvigatel_dspu_140_84_4_exh = models.JSONField(null=True, blank=True, verbose_name=_('ЭЛЕКТРОДВИГАТЕЛЬ ДСПУ-140-84-4 ЭКСГ.'))
    korpus_exh = models.JSONField(blank=True, null=True, verbose_name=_('КОРПУС ЭКСГ.'))
    zadvizhka_exh = models.JSONField(blank=True, null=True, verbose_name=_('ЗАДВИЖКА ЭКСГ.'))
    podshipnik_oporny_exh = models.JSONField(blank=True, null=True, verbose_name=_('ПОДШИПНИК ОПОРНЫЙ ЭКСГ.'))
    podshipnik_oporno_uporny_exh = models.JSONField(blank=True, null=True, verbose_name=_('ПОДШИПНИК ОПОРНО-УПОРНЫЙ ЭКСГ.'))
    maslonasos_shesterenchatyj_rez = models.JSONField(blank=True, null=True, verbose_name=_('МАСЛОНАСОС ШЕСТЕРЕНЧАТЫЙ (РЕЗ.) ЭКСГ.'))
    vk_310s_vibropreobrazovatel_t1 = models.JSONField(blank=True, null=True, verbose_name=_('ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ. Т.1'))
    vk_310s_vibropreobrazovatel_t3 = models.JSONField(blank=True, null=True, verbose_name=_('ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ. Т.3'))
    elektrooborudovaniya_austera = models.JSONField(blank=True, null=True, verbose_name=_('ЭЛЕКТРООБОРУДОВАНИЯ ЭКСГАУСТЕРА'))
    vk_310s_vibropreobrazovatel_t2 = models.JSONField(blank=True, null=True, verbose_name=_('ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ. Т.2'))
    podshipnik_oporny = models.JSONField(blank=True, null=True, verbose_name=_('ПОДШИПНИК ОПОРНЫЙ'))
    reduktor_gaz_zadvizhki_exh = models.JSONField(blank=True, null=True, verbose_name=_('РЕДУКТОР ГАЗ. ЗАДВИЖКИ ЭКСГ.'))
    tiristor_vozbuditel_vt_rem_400_vu1 = models.JSONField(blank=True, null=True, verbose_name=_('ТИРИСТ. ВОЗБУДИТЕЛЬ ВТ-РЭМ-400 ВУ1'))
    zapornaya_armatura_exhaustera = models.JSONField(blank=True, null=True, verbose_name=_('ЗАПОРНАЯ АРМАТУРА ЭКСГАУСТЕРА'))
    masloprovody_exhaustera = models.JSONField(blank=True, null=True, verbose_name=_('МАСЛОПРОВОДЫ ЭКСГАУСТЕРА'))
    gsm_exh = models.JSONField(blank=True, null=True, verbose_name=_('ГСМ ЭКСГ.'))
    tsmt_101_010_50m_80_termopreobr_maslo = models.JSONField(blank=True, null=True, verbose_name=_('ТСМТ-101-010-50М-80 ТЕРМОПРЕОБР.МАСЛО'))
    tr_r_tm_4000_10_6_exh = models.JSONField(blank=True, null=True, verbose_name=_('ТР-Р ТМ-4000-10/6 ЭКСГ.'))
    kl1_tr_do_ed_exhaustera = models.JSONField(blank=True, null=True, verbose_name=_('КЛ1 ТР ДО ЭД ЭКСГАУСТЕРА'))
    kl2_tr_do_ed_exhaustera = models.JSONField(blank=True, null=True, verbose_name=_('КЛ2 ТР ДО ЭД ЭКСГАУСТЕРА'))
    maslonasos_rabochij_exh = models.JSONField(blank=True, null=True, verbose_name=_('МАСЛОНАСОС РАБОЧИЙ ЭКСГ.'))
    rotor_exh = models.JSONField(blank=True, null=True, verbose_name=_('РОТОР ЭКСГ.'))
    metran_100_datchiki_davleniya_exh = models.JSONField(blank=True, null=True, verbose_name=_('МЕТРАН-100 ДАТЧИКИ ДАВЛЕНИЯ ЭКСГ.'))
    dvigatel_puskovogo_maslonasosa_exh = models.JSONField(blank=True, null=True, verbose_name=_('ДВИГАТЕЛЬ ПУСКОВОГО МАСЛОНАСОСА ЭКСГ.'))
    gazovaya_zadvizhka_exhaustera_a_m = models.JSONField(blank=True, null=True, verbose_name=_('ГАЗОВАЯ ЗАДВИЖКА ЭКСГАУСТЕРА А/М'))
    kozhuh_mufty = models.JSONField(blank=True, null=True, verbose_name=_('КОЖУХ МУФТЫ ЭКСГ.'))
    tiristor_vozbuditel_vt_rem_400_vu2 = models.JSONField(blank=True, null=True, verbose_name=_('ТИРИСТ. ВОЗБУДИТЕЛЬ ВТ-РЭМ-400 ВУ2'))
    tsmt_101_010_50m_400_termopr_podsh_t2 = models.JSONField(blank=True, null=True, verbose_name=_('ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.2'))
    dvigatel_rezervnogo_maslonasosa_exh = models.JSONField(blank=True, null=True, verbose_name=_('ДВИГАТЕЛЬ РЕЗЕРВНОГО МАСЛОНАСОСА ЭКСГ.'))
    tsmt_101_010_50m_200_termopr_podsh_t3 = models.JSONField(blank=True, null=True, verbose_name=_('ТСМТ-101-010-50М-200 ТЕРМОПР.ПОДШ.Т.3'))
    exhauster_n_8000_a_m = models.JSONField(blank=True, null=True, verbose_name=_('ЭКСГАУСТЕР Н-8000 А/М'))
    sapfir_22_mdd_razrezhenie_v_kollectore = models.JSONField(blank=True, null=True, verbose_name=_('САПФИР 22 МДД РАЗРЕЖЕНИЕ В КОЛЛЕКТОРЕ'))
    maslobak_exh = models.JSONField(blank=True, null=True, verbose_name=_('МАСЛОБАК ЭКСГ.'))
    elektrooborudovaniya = models.JSONField(blank=True, null=True, verbose_name=_('ЭЛЕКТРООБОРУДОВАНИЯ ЭКСГ'))
    sapfir_22_mdd_perepad_davl_na_ciklone = models.JSONField(blank=True, null=True, verbose_name=_('САПФИР 22 МДД ПЕРЕПАД ДАВЛ. НА ЦИКЛОНЕ'))
    tiristornyj_vozbuditel_tv_400_vu1 = models.JSONField(blank=True, null=True, verbose_name=_('ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ ТВ-400 ВУ1'))
    maslonasos_shesterechchatyj_pusk = models.JSONField(blank=True, null=True, verbose_name=_('МАСЛОНАСОС ШЕСТЕРЕНЧАТЫЙ (ПУСК.) ЭКСГ.'))
    masloprovody_exh = models.JSONField(blank=True, null=True, verbose_name=_('МАСЛОПРОВОДЫ ЭКСГ'))
    ulita_exh = models.JSONField(blank=True, null=True, verbose_name=_('УЛИТА ЭКСГ.'))
    elektroapparatura_exh = models.JSONField(blank=True, null=True, verbose_name=_('ЭЛЕКТРОАППАРАТУРА ЭКСГ.'))
    tsmt_101_010_50m_400_termopr_podsh_t1 = models.JSONField(blank=True, null=True, verbose_name=_('ТСМТ-101-010-50М-400 ТЕРМОПР.ПОДШ.Т.1'))
    zap_i_reg_armatura_exh = models.JSONField(blank=True, null=True, verbose_name=_('ЗАП. И РЕГ. АРМАТУРА ЭКСГ.'))
    ele_dvigatel_gaz_zadvizhki_exh = models.JSONField(blank=True, null=True, verbose_name=_('ЭЛ/ДВИГАТЕЛЬ ГАЗ. ЗАДВИЖКИ ЭКСГ.'))
    maslyanyj_filtr_exhaustera = models.JSONField(blank=True, null=True, verbose_name=_('МАСЛЯНЫЙ ФИЛЬТР ЭКСГАУСТЕРА'))
    vk_310s_vibropreobrazovatel_t4_exh = models.JSONField(blank=True, null=True, verbose_name=_('ВК 310С ВИБРОПРЕОБРАЗОВАТЕЛЬ ЭКСГ. Т.4'))
    reguliruyushchaya_apparatura_austera = models.JSONField(blank=True, null=True, verbose_name=_('РЕГУЛИРУЮЩАЯ АППАРАТУРА ЭКСГАУСТЕРА'))
    maslostantsiya_zhidkoj_smazki_exh = models.JSONField(blank=True, null=True, verbose_name=_('МАСЛОСТАНЦИЯ ЖИДКОЙ СМАЗКИ ЭКСГ.'))
    tr_r_tm_6300_10_6 = models.JSONField(blank=True, null=True, verbose_name=_('ТР-Р ТМ-6300-10/6 ЭКСГ.'))
    tiristornyj_vozbuditel_tv_400_9_vu1 = models.JSONField(blank=True, null=True, verbose_name=_('ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ ТВ-400 9 ВУ1'))
    tiristornyj_vozbuditel_spvd_m10_400_5 = models.JSONField(blank=True, null=True, verbose_name=_('ТИРИСТОРНЫЙ ВОЗБУДИТЕЛЬ СПВД-М10-400-5'))
    exhauster_a_m = models.JSONField(blank=True, null=True, verbose_name=_('ЭКСГАУСТЕР А/М'))
    tsmt_101_010_50m_200_termopr_podsh_t4 = models.JSONField(blank=True, null=True, verbose_name=_('ТСМТ-101-010-50М-200 ТЕРМОПР.ПОДШ.Т.4'))
