version: '3'

volumes:
  bapp_data:
  static_volume:
  .:

services:

  web:
    build: .
    image: registry.gitlab.com/11111111/11111112222:latest
    container_name: bapp_app
    env_file:
      - .env
    volumes:
      - static_volume:/web/app/static
      - .:/web
    expose:
      - 4000
    depends_on:
      - db


  db:
    image: kartoza/postgis:11.0-2.5
    container_name: bapp_db
    env_file:
      - .env
    volumes:
      - bapp_data:/var/lib/postgresql/
    expose:
      - 5432

  nginx:
    image: nginx:1.17.2-alpine
    container_name: bapp_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/web/app/static
    ports:
      - 8000:8000
    depends_on:
      - web


  redis:
    image: redis
    container_name: bapp_redis
    ports:
      - 6379:6379